stages:
  download_data:
    cmd: kaggle competitions download -c ranzcr-clip-catheter-line-classification
      -p data/
    outs:
    - data/ranzcr-clip-catheter-line-classification.zip
    frozen: true
  unzip_train_img:
    cmd: unzip data/ranzcr-clip-catheter-line-classification.zip 'train/*' -d 'data/'
    deps:
    - data/ranzcr-clip-catheter-line-classification.zip
    outs:
    - data/train/
    frozen: true
  unzip_test_img:
    cmd: unzip data/ranzcr-clip-catheter-line-classification.zip 'test/*' -d 'data/'
    deps:
    - data/ranzcr-clip-catheter-line-classification.zip
    outs:
    - data/test/
    frozen: true
  unzip_train_labels:
    cmd: unzip data/ranzcr-clip-catheter-line-classification.zip 'train.csv' -d 'data/'
    deps:
    - data/ranzcr-clip-catheter-line-classification.zip
    outs:
    - data/train.csv
    frozen: true
  unzip_train_annotations:
    cmd: unzip data/ranzcr-clip-catheter-line-classification.zip 'train_annotations.csv'
      -d 'data/'
    deps:
    - data/ranzcr-clip-catheter-line-classification.zip
    outs:
    - data/train_annotations.csv
    frozen: true
  split_train_val:
    cmd: python pipe/create_folds.py
    deps:
    - data/train.csv
    - pipe/create_folds.py
    outs:
    - data/train_folds.csv
  train_model_one:
    cmd: python pipe/train.py
    deps:
    - data/train_folds.csv
    - pipe/train.py
    metrics:
    - metrics/model_one_cv.metric:
        cache: false
