stages:
  download_data:
    cmd:
      kaggle competitions download -c ranzcr-clip-catheter-line-classification
      -p data/
    outs:
      - data/ranzcr-clip-catheter-line-classification.zip
    frozen: true
  unzip_train_img:
    cmd: unzip data/ranzcr-clip-catheter-line-classification.zip 'train/*' -d 'data/'
    deps:
      - data/ranzcr-clip-catheter-line-classification.zip
    outs:
      - data/train/
    frozen: true
  unzip_test_img:
    cmd: unzip data/ranzcr-clip-catheter-line-classification.zip 'test/*' -d 'data/'
    deps:
      - data/ranzcr-clip-catheter-line-classification.zip
    outs:
      - data/test/
    frozen: true
  unzip_train_labels:
    cmd: unzip data/ranzcr-clip-catheter-line-classification.zip 'train.csv' -d 'data/'
    deps:
      - data/ranzcr-clip-catheter-line-classification.zip
    outs:
      - data/train.csv
    frozen: true
  unzip_train_annotations:
    cmd:
      unzip data/ranzcr-clip-catheter-line-classification.zip 'train_annotations.csv'
      -d 'data/'
    deps:
      - data/ranzcr-clip-catheter-line-classification.zip
    outs:
      - data/train_annotations.csv
    frozen: true
  unzip_sample_submission:
    cmd:
      unzip data/ranzcr-clip-catheter-line-classification.zip 'sample_submission.csv'
      -d 'data/'
    deps:
      - data/ranzcr-clip-catheter-line-classification.zip
    outs:
      - data/sample_submission.csv
    frozen: true
  resize_images:
    cmd: python pipe/resize_images.py
    deps:
      - data/train/
      - data/test/
    outs:
      - data/train_128/
      - data/train_192/
      - data/train_256/
      - data/train_384/
      - data/train_512/
      - data/train_768/
      - data/train_1024/
      - data/test_128/
      - data/test_192/
      - data/test_256/
      - data/test_384/
      - data/test_512/
      - data/test_768/
      - data/test_1024/
  create_folds:
    cmd: python pipe/create_folds.py
    deps:
      - data/train.csv
      - pipe/create_folds.py
    outs:
      - data/train_folds.csv
  train_resnet18_128:
    cmd: python pipe/train.py --train_data train_256 --test_data test_256
      --fold -1 --epochs 15 --arch resnet18 --sz 128 --batch_size 128
      --lr 1 --sched onecycle
    deps:
      - data/train_folds.csv
      - pipe/train.py
    outs:
      - models/arch=resnet18_sz=128_fold=0.ckpt
      - models/arch=resnet18_sz=128_fold=1.ckpt
      - models/arch=resnet18_sz=128_fold=2.ckpt
      - models/arch=resnet18_sz=128_fold=3.ckpt
      - models/arch=resnet18_sz=128_fold=4.ckpt
      - subs/oof/arch=resnet18_sz=128_fold=0.csv
      - subs/oof/arch=resnet18_sz=128_fold=1.csv
      - subs/oof/arch=resnet18_sz=128_fold=2.csv
      - subs/oof/arch=resnet18_sz=128_fold=3.csv
      - subs/oof/arch=resnet18_sz=128_fold=4.csv
      - subs/arch=resnet18_sz=128_fold=0.csv
      - subs/arch=resnet18_sz=128_fold=1.csv
      - subs/arch=resnet18_sz=128_fold=2.csv
      - subs/arch=resnet18_sz=128_fold=3.csv
      - subs/arch=resnet18_sz=128_fold=4.csv
    metrics:
      - metrics/arch=resnet18_sz=128.metric:
          cache: false
  train_efficientnet_b4_128:
    cmd: python pipe/train.py --train_data train_128 --test_data test_128
      --fold -1 --epochs 15 --arch tf_efficientnet_b4_ns --sz 128 --batch_size 64
      --lr 1 --sched onecycle
    deps:
      - data/train_folds.csv
      - pipe/train.py
    outs:
      - models/arch=tf_efficientnet_b4_ns_sz=128_fold=0.ckpt
      - models/arch=tf_efficientnet_b4_ns_sz=128_fold=1.ckpt
      - models/arch=tf_efficientnet_b4_ns_sz=128_fold=2.ckpt
      - models/arch=tf_efficientnet_b4_ns_sz=128_fold=3.ckpt
      - models/arch=tf_efficientnet_b4_ns_sz=128_fold=4.ckpt
      - subs/oof/arch=tf_efficientnet_b4_ns_sz=128_fold=0.csv
      - subs/oof/arch=tf_efficientnet_b4_ns_sz=128_fold=1.csv
      - subs/oof/arch=tf_efficientnet_b4_ns_sz=128_fold=2.csv
      - subs/oof/arch=tf_efficientnet_b4_ns_sz=128_fold=3.csv
      - subs/oof/arch=tf_efficientnet_b4_ns_sz=128_fold=4.csv
      - subs/arch=tf_efficientnet_b4_ns_sz=128_fold=0.csv
      - subs/arch=tf_efficientnet_b4_ns_sz=128_fold=1.csv
      - subs/arch=tf_efficientnet_b4_ns_sz=128_fold=2.csv
      - subs/arch=tf_efficientnet_b4_ns_sz=128_fold=3.csv
      - subs/arch=tf_efficientnet_b4_ns_sz=128_fold=4.csv
    metrics:
      - metrics/arch=tf_efficientnet_b4_ns_sz=128.metric:
          cache: false
  train_resnet50_128:
    cmd: python pipe/train.py --train_data train_128 --test_data test_128
      --fold -1 --epochs 15 --arch resnet50 --sz 128 --batch_size 128
      --lr 1 --sched onecycle
    deps:
      - data/train_folds.csv
      - pipe/train.py
    outs:
      - models/arch=resnet50_sz=128_fold=0.ckpt
      - models/arch=resnet50_sz=128_fold=1.ckpt
      - models/arch=resnet50_sz=128_fold=2.ckpt
      - models/arch=resnet50_sz=128_fold=3.ckpt
      - models/arch=resnet50_sz=128_fold=4.ckpt
      - subs/oof/arch=resnet50_sz=128_fold=0.csv
      - subs/oof/arch=resnet50_sz=128_fold=1.csv
      - subs/oof/arch=resnet50_sz=128_fold=2.csv
      - subs/oof/arch=resnet50_sz=128_fold=3.csv
      - subs/oof/arch=resnet50_sz=128_fold=4.csv
      - subs/arch=resnet50_sz=128_fold=0.csv
      - subs/arch=resnet50_sz=128_fold=1.csv
      - subs/arch=resnet50_sz=128_fold=2.csv
      - subs/arch=resnet50_sz=128_fold=3.csv
      - subs/arch=resnet50_sz=128_fold=4.csv
    metrics:
      - metrics/arch=resnet50_sz=128.metric:
          cache: false
  train_efficientnet_b4_256:
    cmd: python pipe/train.py --train_data train_256 --test_data test_256
      --fold -1 --epochs 15 --arch tf_efficientnet_b4_ns --sz 256 --batch_size 22
      --lr 1 --sched onecycle
    deps:
      - data/train_folds.csv
      - pipe/train.py
    outs:
      - models/arch=tf_efficientnet_b4_ns_sz=256_fold=0.ckpt
      - models/arch=tf_efficientnet_b4_ns_sz=256_fold=1.ckpt
      - models/arch=tf_efficientnet_b4_ns_sz=256_fold=2.ckpt
      - models/arch=tf_efficientnet_b4_ns_sz=256_fold=3.ckpt
      - models/arch=tf_efficientnet_b4_ns_sz=256_fold=4.ckpt
      - subs/oof/arch=tf_efficientnet_b4_ns_sz=256_fold=0.csv
      - subs/oof/arch=tf_efficientnet_b4_ns_sz=256_fold=1.csv
      - subs/oof/arch=tf_efficientnet_b4_ns_sz=256_fold=2.csv
      - subs/oof/arch=tf_efficientnet_b4_ns_sz=256_fold=3.csv
      - subs/oof/arch=tf_efficientnet_b4_ns_sz=256_fold=4.csv
      - subs/arch=tf_efficientnet_b4_ns_sz=256_fold=0.csv
      - subs/arch=tf_efficientnet_b4_ns_sz=256_fold=1.csv
      - subs/arch=tf_efficientnet_b4_ns_sz=256_fold=2.csv
      - subs/arch=tf_efficientnet_b4_ns_sz=256_fold=3.csv
      - subs/arch=tf_efficientnet_b4_ns_sz=256_fold=4.csv
    metrics:
      - metrics/arch=tf_efficientnet_b4_ns_sz=256.metric:
          cache: false
  train_resnet18_512:
    cmd: python pipe/train.py --train_data train_512 --test_data test_512
      --fold -1 --epochs 15 --arch resnet18 --sz 512 --auto_batch_size power
      --lr 1 --sched onecycle
    deps:
      - data/train_folds.csv
      - pipe/train.py
    outs:
      - models/arch=resnet18_sz=512_fold=0.ckpt
      - models/arch=resnet18_sz=512_fold=1.ckpt
      - models/arch=resnet18_sz=512_fold=2.ckpt
      - models/arch=resnet18_sz=512_fold=3.ckpt
      - models/arch=resnet18_sz=512_fold=4.ckpt
      - subs/oof/arch=resnet18_sz=512_fold=0.csv
      - subs/oof/arch=resnet18_sz=512_fold=1.csv
      - subs/oof/arch=resnet18_sz=512_fold=2.csv
      - subs/oof/arch=resnet18_sz=512_fold=3.csv
      - subs/oof/arch=resnet18_sz=512_fold=4.csv
      - subs/arch=resnet18_sz=512_fold=0.csv
      - subs/arch=resnet18_sz=512_fold=1.csv
      - subs/arch=resnet18_sz=512_fold=2.csv
      - subs/arch=resnet18_sz=512_fold=3.csv
      - subs/arch=resnet18_sz=512_fold=4.csv
    metrics:
      - metrics/arch=resnet18_sz=512.metric:
          cache: false
